version: '3.1'
services:
  stats-server:
    image: stats-server
    build: explore-with-me-statistic_service/stats-server
    ports:
      - "9090:9090"
    depends_on:
    - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgresql
      - SPRING_DATASOURCE_PASSWORD=admin

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=admin
